apiVersion: apps/v1
kind: ReplicaSet
metdata:
  name: myapp-rs
  labels:
    app: my-app
    type: website
spec:
  template:
    metadata:
      name: mywebsite-pod
      labels:
        app: mywebsite
        type: static
    spec:
      containers:
      - name: mywebsite-container
        image: dhruvin30/dhsoniweb
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  